### ISSUE TITLE
fix: Frontend/UI Fixes for Website Enhancement: Summary Checklist

### ISSUE THREAD

**Issue by dmnktoe** [dmnktoe/duecker-medizintechnik#109]
This issue aims to address various frontend/UI concerns and implement enhancements on our website. The checklist below outlines specific tasks that need attention to improve user experience and resolve existing issues. These changes encompass fixes for layout inconsistencies, navigation glitches, mobile responsiveness, accessibility improvements, and other related UI/UX enhancements.

https://dmnktoe.notion.site/20231121_TodoWebsiteVisuals-5d2cd9619be44841bd4c8a71191576a5?pvs=4

- [x] Ensure the correct container width on the Cookies page.
- [x] Rectify missing/glitchy breadcrumbs on Privacy and Cookies page.
- [x] Investigate and fix intermittent issues with footer navigation functionality.
- [x] #180
- [x] #194
- [x] Adjust the spacing between images, social buttons, and text in blog posts.
- [x] #179
- [x] Implement cookie settings link in the mobile navigation.
- [x] Review and implement necessary Aria screen reader attributes for improved accessibility.
- [x] footer navigation sometimes doesn’t work
- [x] full height responsive menu glitch
- [x] spacing blog post image social and text
- [x] margin headlines
- [x] cookie settings link mobile nav
- [x] einheitlichen style
- [x] hero slideshow
- [x] google performance
- [x] dns prefetch
- [x] complete ui overhaul
- [x] title abstufungen größe - neue font ([[Signifier](https://klim.co.nz/retail-fonts/signifier/)](https://klim.co.nz/retail-fonts/signifier/) & [[Söhne](https://klim.co.nz/collections/soehne/)](https://klim.co.nz/collections/soehne/))
- [x] short overflow in body while page load
- [x] sticky scroll side privacy / container width zu breit
- [x] text responsive `PostsCarousel.tsx`
- [x] new font
- [x] link immer bold???
- [x] mit normaler helvetica alle “bold” semibold etc rausfiltern
- [x] rtl & [[ui ideas](https://www.notion.so/ui-ideas-b8d839db7fdc4835b7ea037c0ed00257?pvs=21)](https://www.notion.so/ui-ideas-b8d839db7fdc4835b7ea037c0ed00257?pvs=21)
- [x] react scroll text animation horizontal
- [x] refactor components make them easier to read and understand
- [x] refactor: footer component
- [x] fix weird green border in cta header button
- [x] fix: layout glitch in hero slideshow on page load
