### ISSUE TITLE
chore: content and internationalize (i18n) checklist

### ISSUE THREAD

**Issue by dmnktoe** [dmnktoe/duecker-medizintechnik#60]
- [x] fix: render breadcrumbs in user-selected language
- [x] refactor: prefix all meta/seo fields with `_`
- [x] feat: internationalize page slugs with middleware
- [x] fix: extract all strings to make them translatable
- [x] finish whole project translation
